### ISSUE TITLE
Questions about DSLP

### ISSUE THREAD

**Issue by guimorg** [dslp/dslp#10]
Hey everyone! 

Great job at the DSLP initiative.

I have a couple of question trying to understand how all the linking of issues happen in the lifecycle of the Data Science Project. How does one link parent issues form a Data Issue to its children?

Also, the Ask Issue is never closed? It remains open and some adjustments are being made when needed? Or there is an output for each issue, like a markdown file?

Thank You!

ps: I tried sending an email to dslp@microsoft.com but it seems that it won't receive e-mails from outside the Microsoft corporation :(

**Comment by charleswm** [comment]
Hi @guimorg. Thanks for reaching out.

Let me try to address each of these.

## Linking Issues

In the Ask issue there is a section for Datasets, this is where you'd link the issues related to creating those datasets.

### Example
______________________________________________________________________________________________
![image](https://user-images.githubusercontent.com/11549389/82968239-d6751a00-9f9a-11ea-98c0-51e352581bed.png)
_____________________________________________________________________________________________________

### Child Issues
If you need multiple issues to complete a Data issue, then you should create subtasks in that issue (using - [ ] and then link those issues to the parent issue.)

### Example (in a data issue)
_______________________________________________________
![image](https://user-images.githubusercontent.com/11549389/82970520-77190900-9f9e-11ea-94b3-505be5a70de5.png)

__________________________________________________________________________

Right now the process for this is admittedly a bit manual, but from our experience it's not too bad. We're working on automating some this going forward (the advantage of issue templates), but we wanted to make sure we had the proper constructs and blueprint down before investing time in doing so.

## When do you close the Ask issue?

As you alluded to, the ask issues will stay open for a while. This is on purpose. The ask issue is the basis of your project, so it should stay open until you solve your problem. This translates to closing it when you release a version of your solution. The definition of that acceptance criteria comes down to the needs of your org. 

One thing to keep in mind is that if you release something, you should close the ask issue. If you need to improve it after that, you should open a new issue to mark that "we already solved this once and now we're trying to improve it. Generally this will look like a stripped down version of an ask issue. We're thinking about creating a template for it as well (an Ask lite???) but didn't want to confuse things too much.

## Issues vs docs and assets

You didn't explicitly ask about this, but it bears mentioning. The issues are for defining and managing your work. Once you actually do the work though, you should capture it as assets in your repository. This could be code, schema definitions, documentation, etc. You want to make sure you're not storing content long-term in your issues because the idea is that you eventually you want to close the issues and not really think about them anymore. This means that if you want content to be persistent, you need to find a way to incorporate it into your repo. This usually means pushing code or documentation.

## Broken Email alias

Thanks for pointing this out. I didn't realize that was the case. I'll check on this first thing in the morning.

**Comment by charleswm** [comment]
@guimorg the email address is fixed.

**Comment by guimorg** [comment]
Hi, @charleswm!

Thank you very much for your response! Also, the 'Issues vs docs and assets' was very helpful 🏅. I've just forked the template repo to test this using a toy project, that way I can have a better understanding of the whole project - and maybe come again with more doubts, but this time I'll reach you guys via e-mail 😆 .

Thanks Again!
