### ISSUE TITLE
folder directory "code" not recommended

### ISSUE THREAD

**Issue by FlorianPydde** [dslp/dslp#21]
Hi team,

I like the the repo structure. However, I would not recommend using "code" for the core modules of the DS work due to the fact that "code" is a core module in python: https://docs.python.org/3.8/library/code.html. 

I would suggest using src, project-name, or something else for it. 

Regards.

**Comment by charleswm** [comment]
Hi Florian,

I don't think this should be a problem because this structure is not for shipping a library, so you would never actually import `code` anywhere in your python scripts, nor would "end users" ever install your repo as a package. (Note the absence of an `__init__.py` in the code directory)

Instead this structure is for shipping models/reports/datasets/etc. that are the output of a data science process. This means the workflow tends to be more geared around building and deploying pipelines or runs that generate artifacts (e.g. model, dataset, report, etc.).

You could optionally have packages/modules within the `code`, but they should be treated as top-level packages. This has the nice side effect of making it harder to tightly couple your code from across the different functions. 

With this in mind, do you still see potential issues with having a `code` directory?

**Comment by FlorianPydde** [comment]
Hi Charles,

Thanks for your quick answer. 

Whether or not the "end users" would/should install the repo as a package is, I think, debatable. Other repos like "Kedro" that creates DS pipelines, ultimately package their code.

It is very common to have a "utils" folder to handle all the security/setup parts like setting up the workspace, getting the keys from KeyVault, etc. I suppose you would recommend to use the namespace approach (sys.path) in this case, right ? If so, It would be helpful to have some guidance on that aspect.

Still, I wouldn't use "code" as a folder name simply because it is a core python module. 

btw, what's the purpose of the setup.py file in your case ?
